# LANGUAGE message translation file for plpython
# Copyright (C) 2010 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 9.1\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2011-11-09 20:40+0000\n"
"PO-Revision-Date: 2011-11-22 11:36-0000\n"
"Last-Translator: Gheorge Rosca Codreanu <max@oceanline.co.uk>\n"
"Language-Team: Română <xsoftware.consultancy@gmail.com>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : 2;\n"
"X-Poedit-Language: Romanian\n"
"X-Poedit-Country: ROMANIA\n"

#: plpython.c:475
#, c-format
msgid "PL/Python function \"%s\""
msgstr "funcție PL/Python \"%s\""

#: plpython.c:482
msgid "PL/Python anonymous code block"
msgstr "bloc de cod PL/Python anonim"

#: plpython.c:489
msgid "while modifying trigger row"
msgstr "în timpul modificării triggerului de rând"

#: plpython.c:496
msgid "while creating return value"
msgstr "în timpul creării valorii rezultat"

#: plpython.c:707
#: plpython.c:733
msgid "unexpected return value from trigger procedure"
msgstr "procedura trigger a rezultat o valoare neașteptată"

#: plpython.c:708
msgid "Expected None or a string."
msgstr "așteptam None sau un șir String"

#: plpython.c:723
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "funcția trigger PL/Python a rezultat \"MODIFY\" întro funcție trigger de tip DELETE  -- ignor"

#: plpython.c:734
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Așteptam None, \"OK\", \"SKIP\", sau \"MODIFY\"."

#: plpython.c:786
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] șters, nu poate modifica rândul "

#: plpython.c:789
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] nu este un dicționar"

#: plpython.c:813
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "TD[\"new\"] cheia dicționarului la poziția %d nu este un șir String"

#: plpython.c:819
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "cheia \"%s\" găsită în TD[\"new\"] nu există ca și coloană în rândul care a activat triggerul"

#: plpython.c:915
msgid "could not create new dictionary while building trigger arguments"
msgstr "nu pot crea un nou dicționar în timp ce construiesc argumentele triggerului"

#: plpython.c:1122
msgid "unsupported set function return mode"
msgstr "mod de returnare a funcției set nesuportat"

#: plpython.c:1123
msgid "PL/Python set-returning functions only support returning only value per call."
msgstr "funcțiile PL/Python ce returnează doar seturi suportă doar o singură valoare returnată la fiecare apel."

#: plpython.c:1135
msgid "returned object cannot be iterated"
msgstr "obiectul returnat nu poate fi iterat"

#: plpython.c:1136
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "funcțiile PL/Python ce returnează seturi trebuie să aibă ca rezultat un obiect iterabil."

#: plpython.c:1161
msgid "error fetching next item from iterator"
msgstr "eroare la obținerea următorului element din iterator"

#: plpython.c:1196
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "funcția PL/Python cu rezultatul de tip \"void\" nu a returbat None"

#: plpython.c:1287
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "intrerupere forţată a unei subtranzacţii din care nu s-a ieşit"

#: plpython.c:1403
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() a eșuat, în timpul creării argumentelor"

#: plpython.c:1407
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() a eșuat, în timpul creării argumentelor"

#: plpython.c:1419
msgid "function returning record called in context that cannot accept type record"
msgstr "apel de funcție care are rezultat de tip rând într-un context care nu acceptă tipul rând"

#: plpython.c:1653
msgid "trigger functions can only be called as triggers"
msgstr "funcţiile trigger pot fi apelate doar ca triggere"

#: plpython.c:1658
#: plpython.c:2131
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "funcțiile PL/Python nu pot returna tipul %s"

#: plpython.c:1740
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "funcțiile PL/Python nu pot accepta tipul %s"

#: plpython.c:1836
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "nu pot compila funcția PL/Python \"%s\""

#: plpython.c:1839
msgid "could not compile anonymous PL/Python code block"
msgstr "nu pot compila codul bloc anonim PL/Python"

#: plpython.c:2133
msgid "PL/Python does not support conversion to arrays of row types."
msgstr "PL/Python nu suportă conversia în array-uri de tip rând."

#: plpython.c:2342
msgid "cannot convert multidimensional array to Python list"
msgstr "nu pot converti un array-ul  mai multe dimensiuni într-o listă Python"

#: plpython.c:2343
msgid "PL/Python only supports one-dimensional arrays."
msgstr "PL/Python suportă doar array-uri cu o dimensiune."

#: plpython.c:2382
msgid "could not create new dictionary"
msgstr "nu pot crea un nou dicționar"

#: plpython.c:2477
msgid "could not create bytes representation of Python object"
msgstr "nu pot crea reprezentarea octet a obiectului Python"

#: plpython.c:2575
msgid "could not create string representation of Python object"
msgstr "nu pot crea reprezentarea șir String a obiectului Python"

#: plpython.c:2586
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "nu pot converti obiectul Python într-un cstring: reprezentarea string a obiectului Python pare să conțină octeți nuli"

#: plpython.c:2620
msgid "return value of function with array return type is not a Python sequence"
msgstr "return value of function with array return type is not a Python sequence"

#: plpython.c:2700
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "cheia \"%s\" nu e gasită în mapare"

#: plpython.c:2701
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Pentru a obșine null într-o coloană, adăugați valoarea None la mapare cu cheia numită cu numele coloanei."

#: plpython.c:2749
msgid "length of returned sequence did not match number of columns in row"
msgstr "lungimea secvenței returnate nu se potrivește cu numărul de coloane din rând"

#: plpython.c:2857
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "atributul \"%s\" nu există în obiectul Python"

#: plpython.c:2858
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Pentru a abține null într-o coloană, obiectul returnat trebuie să aibă un atribut cu numele coloanei și cu valoarea None."

#: plpython.c:3177
msgid "plan.status takes no arguments"
msgstr "plan.status nu acceptă argumente"

#: plpython.c:3301
msgid "second argument of plpy.prepare must be a sequence"
msgstr "al doilea argument al plpy.prepare trebuie să fie o secvență"

#: plpython.c:3351
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: numele tipului la poziția %d nu este un șir"

#: plpython.c:3383
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare nu suportă tipul compozit"

#: plpython.c:3473
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute aștepta o interogare sau un plan"

#: plpython.c:3492
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute acceptă o secvență ca al doilea argument"

#: plpython.c:3508
msgid "could not execute plan"
msgstr "nu pot executa planul"

#: plpython.c:3511
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Secvența așteptată a argumentului %d, a obținut %d: %s"
msgstr[1] "Secvența așteptată a argumentelor %d, a obținut %d: %s"
msgstr[2] "Secvența așteptată a argumentelor %d, a obținut %d: %s"

#: plpython.c:3653
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan a eșuat: %s"

#: plpython.c:3731
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute a eșuat: %s"

#: plpython.c:3786
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "eroare necunoscută în PLy_spi_execute_fetch_result"

#: plpython.c:3848
msgid "this subtransaction has already been entered"
msgstr "am intrat deja în acestă subtranzacţie"

#: plpython.c:3854
#: plpython.c:3906
msgid "this subtransaction has already been exited"
msgstr "am ieşit deja din această subtranzacţie"

#: plpython.c:3900
msgid "this subtransaction has not been entered"
msgstr "nu s-a intrat în această subtranzacţie"

#: plpython.c:3912
msgid "there is no subtransaction to exit from"
msgstr "nu există nici o subtranzacţie din care să ieşim"

#: plpython.c:3994
msgid "could not add the spiexceptions module"
msgstr "nu pot adăuga modulul spiexceptions "

#: plpython.c:4077
msgid "Python major version mismatch in session"
msgstr "nepotrivire în sesiune de versiune majoră Python"

#: plpython.c:4078
#, c-format
msgid "This session has previously used Python major version %d, and it is now attempting to use Python major version %d."
msgstr "Această sesiune a folosit versiunea majoră de Python %d și acum încearcă să folosească versiunea majoră de Python %d."

#: plpython.c:4080
msgid "Start a new session to use a different Python major version."
msgstr "Începe o nouă sesiune pentru a folosi o versiune majoră de Python diferită"

#: plpython.c:4095
msgid "untrapped error in initialization"
msgstr "eroare netratată la inițializare"

#: plpython.c:4123
msgid "could not import \"__main__\" module"
msgstr "nu pot importa modulul \"__main__\""

#: plpython.c:4130
msgid "could not initialize globals"
msgstr "nu pot inițializa globals"

#: plpython.c:4243
msgid "could not parse error message in plpy.elog"
msgstr "nu pot analiza mesajul de eroare în plpy.elog"

#: plpython.c:4267
#: plpython.c:4499
#: plpython.c:4500
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:4854
msgid "could not convert Python Unicode object to PostgreSQL server encoding"
msgstr "nu pot converti obiectul Unicode Python Unicode în codificarea folosită de serverul PostgreSQL"

#~ msgid "PyCObject_AsVoidPtr() failed"
#~ msgstr "PyCObject_AsVoidPtr() a eșuat"

#~ msgid "PyCObject_FromVoidPtr() failed"
#~ msgstr "PyCObject_FromVoidPtr() a eșuat"

#~ msgid "transaction aborted"
#~ msgstr "tranzacție anulată"

#~ msgid "invalid arguments for plpy.prepare"
#~ msgstr "argumente invalide pentru plpy.prepare"

#~ msgid "unrecognized error in PLy_spi_prepare"
#~ msgstr "eroare necunoscută în PLy_spi_prepare"

#~ msgid "unrecognized error in PLy_spi_execute_plan"
#~ msgstr "eroare necunoscută în PLy_spi_execute_plan"

#~ msgid "unrecognized error in PLy_spi_execute_query"
#~ msgstr "eroare necunoscută în PLy_spi_execute_query"

#~ msgid "could not create procedure cache"
#~ msgstr "nu pot crea procedura cache"

#~ msgid "PL/Python: %s"
#~ msgstr "PL/Python: %s"

#~ msgid "out of memory"
#~ msgstr "memorie insuficientă"
